# Generated by Django 6.0.2 on 2026-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=1000)),
                ('newsImage', models.ImageField(upload_to='')),
                ('sources', models.CharField(max_length=50)),
            ],
        ),
    ]
