# Generated by Django 6.0.2 on 2026-02-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
