# Generated by Django 6.0.2 on 2026-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_news_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
